/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanel;

/**
 *
 * @author nicol
 */
public class JPEnvioMensaje extends javax.swing.JPanel{
      private String nombre;
      private String mensaje;
    /**
     * Creates new form JPEnvioMensaje
     */
    public JPEnvioMensaje(String nombre,String mensaje) {
        this.nombre = nombre;
        this.mensaje = mensaje;        
        initComponents();
        nick.setText(nombre);
        jTmensaje.setText(mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTmensaje = new javax.swing.JTextField();
        nick = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTmensaje.setBackground(java.awt.SystemColor.control);
        jTmensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jTmensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmensajeActionPerformed(evt);
            }
        });
        add(jTmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 50));

        nick.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        nick.setText("Nombre");
        add(nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/border_small.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void jTmensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmensajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTmensaje;
    private javax.swing.JLabel nick;
    // End of variables declaration//GEN-END:variables
}
