/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanel;

/**
 *
 * @author nicol
 */
public class JPnotificacionMensaje extends javax.swing.JPanel {
    private String nombre;
    /**
     * Creates new form JPnotificacionMensaje
     */
    public JPnotificacionMensaje(String nombre) {
        this.nombre = nombre;
        initComponents();
        jLnombre.setText(nombre);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/border_small.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 70));

        jLnombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(153, 153, 153));
        add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLnombre;
    // End of variables declaration//GEN-END:variables
}
