/*
 * Programa      : PROYECTO PROGRAMACION INTERACTIVA 2019- DVD RENTAL
 * Fecha         : Septiembre-2019
 * Objetivo      : Información Programa
 * Programadores : Cristhian Guzman, Nathalia Riascos, Vanesa Cifuentes
 * Clase         : Información- Interfaz
 */
package JFrame;

/**
 *
 * @author vanes
 */
public class Informacion extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPingreso = new javax.swing.JPanel();
        jLnombreProf = new javax.swing.JLabel();
        jLfechaActua2 = new javax.swing.JLabel();
        jLyyyy = new javax.swing.JLabel();
        jLnombre1 = new javax.swing.JLabel();
        JlNombre2 = new javax.swing.JLabel();
        JLnombre3 = new javax.swing.JLabel();
        jPresentado = new javax.swing.JLabel();
        JlProf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPingreso.setBackground(new java.awt.Color(255, 255, 255));
        jPingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "     PROYECTO DVD RENTAL     ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Decker", 1, 18), new java.awt.Color(238, 112, 82))); // NOI18N
        jPingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnombreProf.setBackground(new java.awt.Color(238, 112, 82));
        jLnombreProf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLnombreProf.setForeground(new java.awt.Color(51, 51, 51));
        jLnombreProf.setText("Luis Yovanny Romo");
        jPingreso.add(jLnombreProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));
        jPingreso.add(jLfechaActua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 100, 30));

        jLyyyy.setBackground(new java.awt.Color(238, 112, 82));
        jLyyyy.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLyyyy.setForeground(new java.awt.Color(51, 51, 51));
        jLyyyy.setText("2019");
        jPingreso.add(jLyyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLnombre1.setBackground(new java.awt.Color(238, 112, 82));
        jLnombre1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLnombre1.setForeground(new java.awt.Color(51, 51, 51));
        jLnombre1.setText("Cristhian Arvey Guzman");
        jPingreso.add(jLnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        JlNombre2.setBackground(new java.awt.Color(238, 112, 82));
        JlNombre2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JlNombre2.setForeground(new java.awt.Color(51, 51, 51));
        JlNombre2.setText("Nathalia Riascos");
        jPingreso.add(JlNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        JLnombre3.setBackground(new java.awt.Color(238, 112, 82));
        JLnombre3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLnombre3.setForeground(new java.awt.Color(51, 51, 51));
        JLnombre3.setText("Leidy Vanesa Cifuentes");
        jPingreso.add(JLnombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        jPresentado.setBackground(new java.awt.Color(238, 112, 82));
        jPresentado.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jPresentado.setForeground(new java.awt.Color(51, 51, 51));
        jPresentado.setText("Presentado por: ");
        jPingreso.add(jPresentado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));

        JlProf.setBackground(new java.awt.Color(238, 112, 82));
        JlProf.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        JlProf.setForeground(new java.awt.Color(51, 51, 51));
        JlProf.setText("Profesor: ");
        jPingreso.add(JlProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 20));

        jPanel1.add(jPingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnombre3;
    private javax.swing.JLabel JlNombre2;
    private javax.swing.JLabel JlProf;
    private javax.swing.JLabel jLfechaActua2;
    private javax.swing.JLabel jLnombre1;
    private javax.swing.JLabel jLnombreProf;
    private javax.swing.JLabel jLyyyy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPingreso;
    private javax.swing.JLabel jPresentado;
    // End of variables declaration//GEN-END:variables
}
