/*
 * Programa      : PROYECTO PROGRAMACION INTERACTIVA 2019- DVD RENTAL
 * Fecha         : Septiembre-2019
 * Objetivo      : Gestionar actor, mostrar agregar nuevo y borrar
 * Programadores : Cristhian Guzman, Juan Martinez, Nathalia Riascos, Vanesa Cifuentes
 * Clase         : jFactor- Interfaz
 */
package JFrame;

import Modelo.Actor;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class jFactor extends javax.swing.JFrame {

    /**
     * Creates new form jFautor
     */
    public int valor;

    public jFactor() {
        initComponents();
        activarCampos(false);
        jTActorID.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPingreso = new javax.swing.JPanel();
        jTActorID = new javax.swing.JTextField();
        jLNombreActor = new javax.swing.JLabel();
        jLIDActor = new javax.swing.JLabel();
        jLFechaActualizacion = new javax.swing.JLabel();
        jTnombreActor = new javax.swing.JTextField();
        jLFechaActu = new javax.swing.JLabel();
        jLApellidoActor = new javax.swing.JLabel();
        jTApellidoActor = new javax.swing.JTextField();
        jPbotones = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableActores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPingreso.setBackground(new java.awt.Color(255, 255, 255));
        jPingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Actores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Decker", 0, 14), new java.awt.Color(238, 112, 82))); // NOI18N
        jPingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTActorID.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTActorID.setForeground(new java.awt.Color(102, 102, 102));
        jTActorID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPingreso.add(jTActorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 20));

        jLNombreActor.setBackground(new java.awt.Color(238, 112, 82));
        jLNombreActor.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLNombreActor.setForeground(new java.awt.Color(51, 51, 51));
        jLNombreActor.setText("Nombre Actor:");
        jPingreso.add(jLNombreActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jLIDActor.setBackground(new java.awt.Color(238, 112, 82));
        jLIDActor.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLIDActor.setForeground(new java.awt.Color(51, 51, 51));
        jLIDActor.setText("Actores ID:");
        jPingreso.add(jLIDActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLFechaActualizacion.setBackground(new java.awt.Color(238, 112, 82));
        jLFechaActualizacion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLFechaActualizacion.setForeground(new java.awt.Color(51, 51, 51));
        jLFechaActualizacion.setText("Fecha actualización:");
        jPingreso.add(jLFechaActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jTnombreActor.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTnombreActor.setForeground(new java.awt.Color(102, 102, 102));
        jTnombreActor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTnombreActor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTnombreActorFocusGained(evt);
            }
        });
        jPingreso.add(jTnombreActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, -1));
        jPingreso.add(jLFechaActu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 100, 20));

        jLApellidoActor.setBackground(new java.awt.Color(238, 112, 82));
        jLApellidoActor.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLApellidoActor.setForeground(new java.awt.Color(51, 51, 51));
        jLApellidoActor.setText("Apellido Actor:");
        jPingreso.add(jLApellidoActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jTApellidoActor.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTApellidoActor.setForeground(new java.awt.Color(102, 102, 102));
        jTApellidoActor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTApellidoActor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTApellidoActorFocusGained(evt);
            }
        });
        jPingreso.add(jTApellidoActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, -1));

        jPanel1.add(jPingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 330, 200));

        jPbotones.setBackground(new java.awt.Color(255, 255, 255));
        jPbotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPbotones.setForeground(new java.awt.Color(102, 102, 102));
        jPbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBnuevo.setBackground(new java.awt.Color(238, 112, 82));
        jBnuevo.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBnuevo.setForeground(new java.awt.Color(238, 112, 82));
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBnuevo.setContentAreaFilled(false);
        jBnuevo.setDefaultCapable(false);
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPbotones.add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 30));

        jBmodificar.setBackground(new java.awt.Color(238, 112, 82));
        jBmodificar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(238, 112, 82));
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBmodificar.setContentAreaFilled(false);
        jPbotones.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jBeliminar.setBackground(new java.awt.Color(238, 112, 82));
        jBeliminar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(238, 112, 82));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBeliminar.setContentAreaFilled(false);
        jPbotones.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 30));

        jPanel1.add(jPbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 330, 50));

        jTableActores.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTableActores.setForeground(new java.awt.Color(51, 51, 51));
        jTableActores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Actor", "Nombre Actor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableActores);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 330, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jTApellidoActorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTApellidoActorFocusGained
        // TODO add your handling code here:
        if (jTApellidoActor.getText().equalsIgnoreCase("Campo Requerido")) {
            jTApellidoActor.setForeground(Color.BLACK);
            jTApellidoActor.setText("");
        }
    }//GEN-LAST:event_jTApellidoActorFocusGained

    private void jTnombreActorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnombreActorFocusGained
        // TODO add your handling code here:

        if (jTnombreActor.getText().equalsIgnoreCase("Campo Requerido")) {
            jTnombreActor.setForeground(Color.BLACK);
            jTnombreActor.setText("");
        }
    }//GEN-LAST:event_jTnombreActorFocusGained

    public JButton getjBeliminar() {
        return jBeliminar;
    }

    public JButton getjBmodificar() {
        return jBmodificar;
    }

    public JButton getjBnuevo() {
        return jBnuevo;
    }

    public JTextField getjTActorID() {
        return jTActorID;
    }

    public JTextField getjTApellidoActor() {
        return jTApellidoActor;
    }

    public JTable getjTableActores() {
        return jTableActores;
    }

    public JTextField getjTnombreActor() {
        return jTnombreActor;
    }

    public void setjLFechaActu(JLabel jLFechaActu) {
        this.jLFechaActu = jLFechaActu;
    }

    public JLabel getjLFechaActu() {
        return jLFechaActu;
    }

    public void activarCampos(Boolean b) {

        jTnombreActor.setEnabled(b);
        jTApellidoActor.setEnabled(b);

    }

    public void setearCampos() {
        jTActorID.setText("");
        jTnombreActor.setText("");
        jTApellidoActor.setText("");

    }

    public void nuevaAccion() {
        activarCampos(false);
        setearCampos();
        jBnuevo.setText("Nuevo");
        jBmodificar.setText("Modificar");
        jBeliminar.setVisible(true);
    }

    //Escuchas
    public void addListenerBtnNuevo(ActionListener listenActor) {

        jBnuevo.addActionListener(listenActor);
    }

    public void addListenerBtnEliminar(ActionListener listenActor) {

        jBeliminar.addActionListener(listenActor);
    }

    public void addListenerBtnModificar(ActionListener listenActor) {
        jBmodificar.addActionListener(listenActor);
    }

    public void addMouseListenerTabla(MouseListener listenActor) {
        jTableActores.addMouseListener(listenActor);
    }

    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }

    private void limpiarListadoTabla() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTableActores.getModel();
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    //Método para cargar los actores a la tabla 
    public void cargarActorTabla(ArrayList<Actor> listadoActores) {
        DefaultTableModel model_actor;
        model_actor = (DefaultTableModel) jTableActores.getModel();
        limpiarListadoTabla();
        for (int i = 0; i < listadoActores.size(); i++) {
            model_actor.addRow(new Object[]{
                listadoActores.get(i).getActorID(),
                listadoActores.get(i).getNombreActor()});
        }

        valor = Integer.parseInt("" + model_actor.getValueAt(model_actor.getRowCount() - 1, 0)) + 1;

    }

    public int validarCampos() {
        int rtdo = 1;

        if (jTnombreActor.getText().equals("") || jTnombreActor.getText().equals("Campo Requerido")) {

            rtdo = 0;
            mostrarCamposVacios(jTnombreActor);

        }
        if (jTApellidoActor.getText().equals("") || jTApellidoActor.getText().equals("Campo Requerido")) {
            rtdo = 0;

            mostrarCamposVacios(jTApellidoActor);
        }

        return rtdo;
    }

    public void mostrarCamposVacios(JTextField jt) {
        jt.setForeground(Color.red);
        jt.setText("Campo Requerido");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFactor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFactor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JLabel jLApellidoActor;
    private javax.swing.JLabel jLFechaActu;
    private javax.swing.JLabel jLFechaActualizacion;
    private javax.swing.JLabel jLIDActor;
    private javax.swing.JLabel jLNombreActor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPingreso;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTActorID;
    private javax.swing.JTextField jTApellidoActor;
    private javax.swing.JTable jTableActores;
    private javax.swing.JTextField jTnombreActor;
    // End of variables declaration//GEN-END:variables
}
