/*
 * Programa      : PROYECTO PROGRAMACION INTERACTIVA 2019- DVD RENTAL
 * Fecha         : Septiembre-2019
 * Objetivo      : Gestionar ciudad, mostrar agregar nuevo y borrar
 * Programadores : Cristhian Guzman,  Nathalia Riascos, Vanesa Cifuentes
 * Clase         : jFciudad- Interfaz
 */
package JFrame;

//import Controlador.ControllerPais;
import Modelo.Ciudad;
import Modelo.Lenguaje;
import Modelo.Pais;
import Modelo.PaisDAO;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanes
 */
public class jFCiudad extends javax.swing.JFrame {

    /**
     * Creates new form jFCiudad2
     */
    public int valor;
    
    public jFCiudad() {
        initComponents();
        activarCampos(false);
        jTCiudadID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPingreso = new javax.swing.JPanel();
        jTCiudadID = new javax.swing.JTextField();
        jLnombreCiudad = new javax.swing.JLabel();
        jLCiudadID = new javax.swing.JLabel();
        jTnombreciudad = new javax.swing.JTextField();
        jLFechaActualiza = new javax.swing.JLabel();
        jLfechaActua2 = new javax.swing.JLabel();
        jLfechaActua = new javax.swing.JLabel();
        jLPais = new javax.swing.JLabel();
        jCBPais = new javax.swing.JComboBox<>();
        jBtnIngresoPais = new javax.swing.JButton();
        jPbotones = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCiudad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPingreso.setBackground(new java.awt.Color(255, 255, 255));
        jPingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ciudad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Decker", 0, 14), new java.awt.Color(238, 112, 82))); // NOI18N
        jPingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTCiudadID.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTCiudadID.setForeground(new java.awt.Color(102, 102, 102));
        jTCiudadID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTCiudadID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCiudadIDActionPerformed(evt);
            }
        });
        jPingreso.add(jTCiudadID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 20));

        jLnombreCiudad.setBackground(new java.awt.Color(238, 112, 82));
        jLnombreCiudad.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLnombreCiudad.setForeground(new java.awt.Color(51, 51, 51));
        jLnombreCiudad.setText("Ciudad: ");
        jPingreso.add(jLnombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLCiudadID.setBackground(new java.awt.Color(238, 112, 82));
        jLCiudadID.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLCiudadID.setForeground(new java.awt.Color(51, 51, 51));
        jLCiudadID.setText("Ciudad ID:");
        jPingreso.add(jLCiudadID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jTnombreciudad.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTnombreciudad.setForeground(new java.awt.Color(102, 102, 102));
        jTnombreciudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTnombreciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTnombreciudadFocusGained(evt);
            }
        });
        jTnombreciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreciudadActionPerformed(evt);
            }
        });
        jPingreso.add(jTnombreciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, -1));

        jLFechaActualiza.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLFechaActualiza.setForeground(new java.awt.Color(51, 51, 51));
        jLFechaActualiza.setText("Fecha actualización:");
        jPingreso.add(jLFechaActualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPingreso.add(jLfechaActua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 100, 30));
        jPingreso.add(jLfechaActua, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 30));

        jLPais.setBackground(new java.awt.Color(238, 112, 82));
        jLPais.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLPais.setForeground(new java.awt.Color(51, 51, 51));
        jLPais.setText("País: ");
        jPingreso.add(jLPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jCBPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPingreso.add(jCBPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        jBtnIngresoPais.setText("Ingresar");
        jBtnIngresoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresoPaisActionPerformed(evt);
            }
        });
        jPingreso.add(jBtnIngresoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 80, 30));

        jPanel1.add(jPingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 180));

        jPbotones.setBackground(new java.awt.Color(255, 255, 255));
        jPbotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPbotones.setForeground(new java.awt.Color(102, 102, 102));
        jPbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBnuevo.setBackground(new java.awt.Color(238, 112, 82));
        jBnuevo.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBnuevo.setForeground(new java.awt.Color(238, 112, 82));
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBnuevo.setContentAreaFilled(false);
        jBnuevo.setDefaultCapable(false);
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPbotones.add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 30));

        jBmodificar.setBackground(new java.awt.Color(238, 112, 82));
        jBmodificar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(238, 112, 82));
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBmodificar.setContentAreaFilled(false);
        jPbotones.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jBeliminar.setBackground(new java.awt.Color(238, 112, 82));
        jBeliminar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(238, 112, 82));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBeliminar.setContentAreaFilled(false);
        jPbotones.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 30));

        jPanel1.add(jPbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 60));

        jTableCiudad.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTableCiudad.setForeground(new java.awt.Color(51, 51, 51));
        jTableCiudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Ciudad", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableCiudad);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCiudadIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCiudadIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCiudadIDActionPerformed

    private void jTnombreciudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnombreciudadFocusGained
        // TODO add your handling code here:

        if (jTnombreciudad.getText().equalsIgnoreCase("Campo Requerido")) {
            //jTnombreciudad.setForeground(Color.BLACK);
            jTnombreciudad.setText("");
        }
    }//GEN-LAST:event_jTnombreciudadFocusGained

    private void jTnombreciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreciudadActionPerformed

    private void jBtnIngresoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresoPaisActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnIngresoPaisActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    public JButton getjBtnIngresoPais() {
        return jBtnIngresoPais;
    }

    public JComboBox<String> getjCBPais() {
        return jCBPais;
    }

    public JTextField getjTCiudadID() {
        return jTCiudadID;
    }

    public JTextField getjTnombreciudad() {
        return jTnombreciudad;
    }

    public JTable getjTableCiudad() {
        return jTableCiudad;
    }

    public JLabel getjLfechaActua() {
        return jLfechaActua;
    }

    public void activarCampos(Boolean b) {
        jTnombreciudad.setEnabled(b);
        //jTLenguajeID.setEnabled(b);
    }

    public void setearCampos() {

        jTnombreciudad.setText("");
        jTCiudadID.setText("");
        jLFechaActualiza.setText("");
        
    }

    public void nuevaAccion() {
        activarCampos(false);
        setearCampos();
        jBnuevo.setText("Nuevo");
        jBmodificar.setText("Modificar");
        jBeliminar.setVisible(true);
    }

    public JButton getjBeliminar() {
        return jBeliminar;
    }

    public JButton getjBmodificar() {
        return jBmodificar;
    }

    public JButton getjBnuevo() {
        return jBnuevo;
    }
    
    public void addListenerBtnNuevo(ActionListener listenCiudad) {

        jBnuevo.addActionListener(listenCiudad);
    }

    public void addListenerBtnEliminar(ActionListener listenCiudad) {

        jBeliminar.addActionListener(listenCiudad);
    }

    public void addListenerBtnModificar(ActionListener listenCiudad) {
        jBmodificar.addActionListener(listenCiudad);
    }

    public void addMouseListenerTabla(MouseListener listenCiudad) {
        jTableCiudad.addMouseListener(listenCiudad);
    }
    
    //
    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }

    private void limpiarListadoTabla() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTableCiudad.getModel();
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    //Método para cargar los ciudades a la tabla 
    public void cargarCiudadesTabla(ArrayList<Ciudad> listadoCiudad) {
        DefaultTableModel model_ciudad;
        model_ciudad = (DefaultTableModel) jTableCiudad.getModel();
        limpiarListadoTabla();
        for (int i = 0; i < listadoCiudad.size(); i++) {
            model_ciudad.addRow(new Object[]{
                listadoCiudad.get(i).getID_ciudad(),
                listadoCiudad.get(i).getCiudad()});
        }

        valor = Integer.parseInt("" + model_ciudad.getValueAt(model_ciudad.getRowCount() - 1, 0)) + 1;

    }
    
    //Método para cargar paises un combobox
    public void cargarPaisesCombo(ArrayList<Pais> listadoPaises) {
        DefaultComboBoxModel model;
        String[] arregloPaises = new String[listadoPaises.size()];

        for (int a = 0; a < listadoPaises.size(); a++) {
            arregloPaises[a] = listadoPaises.get(a).getPais();
        }

        model = new DefaultComboBoxModel(arregloPaises);

        jCBPais.setModel(model);

    }
    
    
    public int validarCampos()
    {
        int rtdo = 1;

        if (jTnombreciudad.getText().equals("") || jTnombreciudad.getText().equals("Campo Requerido")) {

            rtdo = 0;
           // jTnombreciudad..setForeground(java.awt.Color.red);
            jTnombreciudad.setText("Campo Requerido");

        }
        

        return rtdo;
    }
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBtnIngresoPais;
    private javax.swing.JComboBox<String> jCBPais;
    private javax.swing.JLabel jLCiudadID;
    private javax.swing.JLabel jLFechaActualiza;
    private javax.swing.JLabel jLPais;
    private javax.swing.JLabel jLfechaActua;
    private javax.swing.JLabel jLfechaActua2;
    private javax.swing.JLabel jLnombreCiudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPingreso;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTCiudadID;
    private javax.swing.JTable jTableCiudad;
    private javax.swing.JTextField jTnombreciudad;
    // End of variables declaration//GEN-END:variables
}
