/*
 * Programa      : PROYECTO PROGRAMACION INTERACTIVA 2019- DVD RENTAL
 * Fecha         : Septiembre-2019
 * Objetivo      : Gestionar país, mostrar agregar nuevo y borrar
 * Programadores : Cristhian Guzman, Nathalia Riascos, Vanesa Cifuentes
 * Clase         : jFpais- Interfaz
 */
package JFrame;

import Modelo.Pais;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class jFpais extends javax.swing.JFrame {

    /**
     * Creates new form jFdireccion
     */
    public int valor;

    public jFpais() {
        initComponents();
        activarCampos(false);
        jTPaisID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPingreso = new javax.swing.JPanel();
        jTPaisID = new javax.swing.JTextField();
        jLnombrePais = new javax.swing.JLabel();
        jLPaisID = new javax.swing.JLabel();
        jTnombrePais = new javax.swing.JTextField();
        jLFechaActualiza = new javax.swing.JLabel();
        jLfechaActua2 = new javax.swing.JLabel();
        jLfechaActua = new javax.swing.JLabel();
        jPbotones = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePais = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPingreso.setBackground(new java.awt.Color(255, 255, 255));
        jPingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "País", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Decker", 0, 14), new java.awt.Color(238, 112, 82))); // NOI18N
        jPingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTPaisID.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTPaisID.setForeground(new java.awt.Color(102, 102, 102));
        jTPaisID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTPaisID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPaisIDActionPerformed(evt);
            }
        });
        jPingreso.add(jTPaisID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, 20));

        jLnombrePais.setBackground(new java.awt.Color(238, 112, 82));
        jLnombrePais.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLnombrePais.setForeground(new java.awt.Color(51, 51, 51));
        jLnombrePais.setText("Dirección: ");
        jPingreso.add(jLnombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLPaisID.setBackground(new java.awt.Color(238, 112, 82));
        jLPaisID.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLPaisID.setForeground(new java.awt.Color(51, 51, 51));
        jLPaisID.setText("País ID:");
        jPingreso.add(jLPaisID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jTnombrePais.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTnombrePais.setForeground(new java.awt.Color(102, 102, 102));
        jTnombrePais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTnombrePais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTnombrePaisFocusGained(evt);
            }
        });
        jTnombrePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombrePaisActionPerformed(evt);
            }
        });
        jPingreso.add(jTnombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 200, -1));

        jLFechaActualiza.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLFechaActualiza.setForeground(new java.awt.Color(51, 51, 51));
        jLFechaActualiza.setText("Fecha actualización:");
        jPingreso.add(jLFechaActualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPingreso.add(jLfechaActua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 100, 30));
        jPingreso.add(jLfechaActua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 30));

        jPanel1.add(jPingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 140));

        jPbotones.setBackground(new java.awt.Color(255, 255, 255));
        jPbotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPbotones.setForeground(new java.awt.Color(102, 102, 102));
        jPbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBnuevo.setBackground(new java.awt.Color(238, 112, 82));
        jBnuevo.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBnuevo.setForeground(new java.awt.Color(238, 112, 82));
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBnuevo.setContentAreaFilled(false);
        jBnuevo.setDefaultCapable(false);
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPbotones.add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 30));

        jBmodificar.setBackground(new java.awt.Color(238, 112, 82));
        jBmodificar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(238, 112, 82));
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBmodificar.setContentAreaFilled(false);
        jPbotones.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jBeliminar.setBackground(new java.awt.Color(238, 112, 82));
        jBeliminar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(238, 112, 82));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBeliminar.setContentAreaFilled(false);
        jPbotones.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 30));

        jPanel1.add(jPbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, 50));

        jTablePais.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTablePais.setForeground(new java.awt.Color(51, 51, 51));
        jTablePais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID País", "País"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePais);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 320, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTnombrePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombrePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombrePaisActionPerformed

    private void jTPaisIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPaisIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPaisIDActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jTnombrePaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnombrePaisFocusGained
        // TODO add your handling code here:

        if (jTnombrePais.getText().equalsIgnoreCase("Campo Requerido")) {
            jTnombrePais.setForeground(Color.BLACK);
            jTnombrePais.setText("");
        }
    }//GEN-LAST:event_jTnombrePaisFocusGained

    public void activarCampos(Boolean b) {
        jTnombrePais.setEnabled(b);
       
    }

    public void setearCampos() {

        jTnombrePais.setText("");
        jTPaisID.setText("");
        jLFechaActualiza.setText("");

    }

    public void nuevaAccion() {
        activarCampos(false);
        setearCampos();
        jBnuevo.setText("Nuevo");
        jBmodificar.setText("Modificar");
        jBeliminar.setVisible(true);
    }

    public JButton getjBmodificar() {
        return jBmodificar;
    }

    public JButton getjBnuevo() {
        return jBnuevo;
    }

    public JButton getjBeliminar() {
        return jBeliminar;
    }

    public JTextField getjTPaisID() {
        return jTPaisID;
    }

    public JTable getjTablePais() {
        return jTablePais;
    }

    public void setjTPaisID(JTextField jTPaisID) {
        this.jTPaisID = jTPaisID;
    }

    public JLabel getjLfechaActua() {
        return jLfechaActua;
    }

    public JTextField getjTnombrePais() {
        return jTnombrePais;
    }

    private void limpiarListadoTabla() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTablePais.getModel();
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    //Método para cargar los paises a la tabla 
    public void cargarPaisTabla(ArrayList<Pais> listadoPais) {
        DefaultTableModel model_pais;
        model_pais = (DefaultTableModel) jTablePais.getModel();
        limpiarListadoTabla();
        for (int i = 0; i < listadoPais.size(); i++) {
            model_pais.addRow(new Object[]{
                listadoPais.get(i).getPais_id(),
                listadoPais.get(i).getPais()});
        }

        valor = Integer.parseInt("" + model_pais.getValueAt(model_pais.getRowCount() - 1, 0)) + 1;

    }

    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }

    public void addListenerBtnNuevo(ActionListener listenpais) {
        jBnuevo.addActionListener(listenpais);
    }

    public void addListenerBtnEliminar(ActionListener listenLenguaje) {
        jBeliminar.addActionListener(listenLenguaje);
    }

    public void addListenerBtnModificar(ActionListener listenLenguaje) {
        jBmodificar.addActionListener(listenLenguaje);
    }

    public void addMouseListenerTabla(MouseListener listenLenguaje) {
        jTablePais.addMouseListener(listenLenguaje);
    }

    //Validar y cambiar campos a rojo
    public int validarCampos() {
        int rtdo = 1;

        if (jTnombrePais.getText().equals("") || jTnombrePais.getText().equals("Campo Requerido")) {

            rtdo = 0;
            jTnombrePais.setForeground(Color.red);
            jTnombrePais.setText("Campo Requerido");

        }

        return rtdo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFpais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFpais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFpais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFpais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFpais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JLabel jLFechaActualiza;
    private javax.swing.JLabel jLPaisID;
    private javax.swing.JLabel jLfechaActua;
    private javax.swing.JLabel jLfechaActua2;
    private javax.swing.JLabel jLnombrePais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPingreso;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTPaisID;
    private javax.swing.JTable jTablePais;
    private javax.swing.JTextField jTnombrePais;
    // End of variables declaration//GEN-END:variables
}
