/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Modelo.Pelicula;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author nicol
 */
public class iFalquiler extends javax.swing.JInternalFrame {

    /**
     * Creates new form iFalquiler
     */
    DefaultListModel modelo;

    public iFalquiler() {
        initComponents();
        modelo = new DefaultListModel();
        jListBusquedaPeliculas.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSinopsis = new javax.swing.JLabel();
        jLSinopsisTexto = new javax.swing.JLabel();
        jPinformacionPeliculs = new javax.swing.JPanel();
        jLidAlquiler = new javax.swing.JLabel();
        jLtitulo = new javax.swing.JLabel();
        jLprecio = new javax.swing.JLabel();
        jLduracion = new javax.swing.JLabel();
        jLsinopsis = new javax.swing.JLabel();
        jLidPelicula = new javax.swing.JLabel();
        jTIDAlquiler = new javax.swing.JTextField();
        jTIDPelicula = new javax.swing.JTextField();
        jTxTitulo = new javax.swing.JTextField();
        jTPrecio = new javax.swing.JTextField();
        jTDuracion = new javax.swing.JTextField();
        jLctegoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBusquedaPeliculas = new javax.swing.JList<>();
        jPbotones1 = new javax.swing.JPanel();
        jBAlquilar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBmodificar1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscador3.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 50, 40));

        jTBuscador.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTBuscador.setForeground(new java.awt.Color(102, 102, 102));
        jTBuscador.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBuscadorActionPerformed(evt);
            }
        });
        jTBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscadorKeyReleased(evt);
            }
        });
        jPanel2.add(jTBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 390, 40));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Buscar:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 60, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 710, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 240));

        jLabelSinopsis.setBackground(new java.awt.Color(238, 112, 82));
        jLabelSinopsis.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelSinopsis.setForeground(new java.awt.Color(238, 112, 82));
        jLabelSinopsis.setText("Sinopsis:");
        jPanel4.add(jLabelSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jLSinopsisTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.add(jLSinopsisTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 600, 90));

        jPinformacionPeliculs.setBackground(new java.awt.Color(255, 255, 255));
        jPinformacionPeliculs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLidAlquiler.setBackground(new java.awt.Color(238, 112, 82));
        jLidAlquiler.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLidAlquiler.setForeground(new java.awt.Color(238, 112, 82));
        jLidAlquiler.setText("ID Alquiler:");
        jPinformacionPeliculs.add(jLidAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLtitulo.setBackground(new java.awt.Color(238, 112, 82));
        jLtitulo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(238, 112, 82));
        jLtitulo.setText("Título:");
        jLtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPinformacionPeliculs.add(jLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 30));

        jLprecio.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLprecio.setForeground(new java.awt.Color(238, 112, 82));
        jLprecio.setText("Precio:");
        jPinformacionPeliculs.add(jLprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLduracion.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLduracion.setForeground(new java.awt.Color(238, 112, 82));
        jLduracion.setText("Duración:");
        jPinformacionPeliculs.add(jLduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        jLsinopsis.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLsinopsis.setForeground(new java.awt.Color(238, 112, 82));
        jLsinopsis.setText("Actores:");
        jPinformacionPeliculs.add(jLsinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLidPelicula.setBackground(new java.awt.Color(238, 112, 82));
        jLidPelicula.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLidPelicula.setForeground(new java.awt.Color(238, 112, 82));
        jLidPelicula.setText("ID pelicula:");
        jPinformacionPeliculs.add(jLidPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPinformacionPeliculs.add(jTIDAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, 20));
        jPinformacionPeliculs.add(jTIDPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 200, 20));
        jPinformacionPeliculs.add(jTxTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 200, 20));
        jPinformacionPeliculs.add(jTPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, 20));
        jPinformacionPeliculs.add(jTDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, 20));

        jLctegoria.setBackground(new java.awt.Color(238, 112, 82));
        jLctegoria.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLctegoria.setForeground(new java.awt.Color(238, 112, 82));
        jLctegoria.setText("Categoría:");
        jPinformacionPeliculs.add(jLctegoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPanel4.add(jPinformacionPeliculs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 460, 270));

        jScrollPane1.setViewportView(jListBusquedaPeliculas);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 390, 100));

        jPbotones1.setBackground(new java.awt.Color(255, 255, 255));
        jPbotones1.setForeground(new java.awt.Color(102, 102, 102));
        jPbotones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBAlquilar.setBackground(new java.awt.Color(238, 112, 82));
        jBAlquilar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBAlquilar.setForeground(new java.awt.Color(238, 112, 82));
        jBAlquilar.setText("Alquilar");
        jBAlquilar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBAlquilar.setContentAreaFilled(false);
        jBAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlquilarActionPerformed(evt);
            }
        });
        jPbotones1.add(jBAlquilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 30));

        jBeliminar.setBackground(new java.awt.Color(238, 112, 82));
        jBeliminar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(238, 112, 82));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBeliminar.setContentAreaFilled(false);
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPbotones1.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 70, 30));

        jBmodificar1.setBackground(new java.awt.Color(238, 112, 82));
        jBmodificar1.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBmodificar1.setForeground(new java.awt.Color(238, 112, 82));
        jBmodificar1.setText("Modificar");
        jBmodificar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBmodificar1.setContentAreaFilled(false);
        jBmodificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificar1ActionPerformed(evt);
            }
        });
        jPbotones1.add(jBmodificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, 30));

        jPanel4.add(jPbotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 420, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlquilarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAlquilarActionPerformed

    private void jBmodificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmodificar1ActionPerformed

    private void jTBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscadorKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTBuscadorKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscadorActionPerformed

    //Método para cargar al JList el listado por nombre de Pelicula
    public void cargarPeliculasLista(ArrayList<Pelicula> listaPelicula) {
        modelo.removeAllElements();
        for (int i = 0; i < listaPelicula.size(); i++) {
            modelo.addElement(listaPelicula.get(i).getTitulo());

        }
        
    }

    public JTextField getjTBuscador() {
        return jTBuscador;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlquilar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLSinopsisTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelSinopsis;
    private javax.swing.JLabel jLctegoria;
    private javax.swing.JLabel jLduracion;
    private javax.swing.JLabel jLidAlquiler;
    private javax.swing.JLabel jLidPelicula;
    private javax.swing.JList<String> jListBusquedaPeliculas;
    private javax.swing.JLabel jLprecio;
    private javax.swing.JLabel jLsinopsis;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPbotones1;
    private javax.swing.JPanel jPinformacionPeliculs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscador;
    private javax.swing.JTextField jTDuracion;
    private javax.swing.JTextField jTIDAlquiler;
    private javax.swing.JTextField jTIDPelicula;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTextField jTxTitulo;
    // End of variables declaration//GEN-END:variables
}
