/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Modelo.*;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class iFcliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form iFcliente
     */
    public iFcliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPingreso = new javax.swing.JPanel();
        jTCuentaActivoBool = new javax.swing.JTextField();
        jTClienteID = new javax.swing.JTextField();
        jLTienda = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jLactivo = new javax.swing.JLabel();
        jTnombreCliente = new javax.swing.JTextField();
        jTCorreoCliente = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jLCuentaActivoBool = new javax.swing.JLabel();
        jLfechaCreacion = new javax.swing.JLabel();
        jTFechaCreacion = new javax.swing.JTextField();
        jTActivoInt = new javax.swing.JTextField();
        jLCorreo = new javax.swing.JLabel();
        jLDireccion = new javax.swing.JLabel();
        jBTienda = new javax.swing.JButton();
        jLApellidos = new javax.swing.JLabel();
        jTApellidos = new javax.swing.JTextField();
        jComboBoxTienda = new javax.swing.JComboBox<>();
        jBIngresoDireccion = new javax.swing.JButton();
        jPtabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jPbotones = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPingreso.setBackground(new java.awt.Color(255, 255, 255));
        jPingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Decker", 0, 14), new java.awt.Color(238, 112, 82))); // NOI18N
        jPingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTCuentaActivoBool.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTCuentaActivoBool.setForeground(new java.awt.Color(102, 102, 102));
        jTCuentaActivoBool.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTCuentaActivoBool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCuentaActivoBoolActionPerformed(evt);
            }
        });
        jPingreso.add(jTCuentaActivoBool, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 240, 20));

        jTClienteID.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTClienteID.setForeground(new java.awt.Color(102, 102, 102));
        jTClienteID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTClienteIDActionPerformed(evt);
            }
        });
        jPingreso.add(jTClienteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 20));

        jLTienda.setBackground(new java.awt.Color(238, 112, 82));
        jLTienda.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLTienda.setForeground(new java.awt.Color(51, 51, 51));
        jLTienda.setText("Tienda:");
        jPingreso.add(jLTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        jLNombre.setBackground(new java.awt.Color(238, 112, 82));
        jLNombre.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLNombre.setText("Nombres:");
        jPingreso.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLCliente.setBackground(new java.awt.Color(238, 112, 82));
        jLCliente.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLCliente.setForeground(new java.awt.Color(51, 51, 51));
        jLCliente.setText("Cliente ID:");
        jPingreso.add(jLCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLactivo.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLactivo.setForeground(new java.awt.Color(51, 51, 51));
        jLactivo.setText("Activo:");
        jPingreso.add(jLactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jTnombreCliente.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTnombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        jTnombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreClienteActionPerformed(evt);
            }
        });
        jPingreso.add(jTnombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, -1));

        jTCorreoCliente.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTCorreoCliente.setForeground(new java.awt.Color(102, 102, 102));
        jTCorreoCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTCorreoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCorreoClienteActionPerformed(evt);
            }
        });
        jPingreso.add(jTCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 20));

        jTDireccion.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTDireccion.setForeground(new java.awt.Color(102, 102, 102));
        jTDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDireccionActionPerformed(evt);
            }
        });
        jPingreso.add(jTDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 140, 20));

        jLCuentaActivoBool.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLCuentaActivoBool.setText("Cuenta Activo:");
        jPingreso.add(jLCuentaActivoBool, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLfechaCreacion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLfechaCreacion.setForeground(new java.awt.Color(51, 51, 51));
        jLfechaCreacion.setText("Fecha Creacion:");
        jPingreso.add(jLfechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jTFechaCreacion.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTFechaCreacion.setForeground(new java.awt.Color(102, 102, 102));
        jTFechaCreacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTFechaCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaCreacionActionPerformed(evt);
            }
        });
        jPingreso.add(jTFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 240, 20));

        jTActivoInt.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTActivoInt.setForeground(new java.awt.Color(102, 102, 102));
        jTActivoInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTActivoInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTActivoIntActionPerformed(evt);
            }
        });
        jPingreso.add(jTActivoInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 240, 20));

        jLCorreo.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLCorreo.setForeground(new java.awt.Color(51, 51, 51));
        jLCorreo.setText("Correo:");
        jPingreso.add(jLCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 50, -1));

        jLDireccion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jLDireccion.setText("Direccion:");
        jPingreso.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jBTienda.setText("Ingresar");
        jBTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTiendaActionPerformed(evt);
            }
        });
        jPingreso.add(jBTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, 30));

        jLApellidos.setBackground(new java.awt.Color(238, 112, 82));
        jLApellidos.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLApellidos.setForeground(new java.awt.Color(51, 51, 51));
        jLApellidos.setText("Apellidos:");
        jPingreso.add(jLApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jTApellidos.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTApellidos.setForeground(new java.awt.Color(102, 102, 102));
        jTApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidosActionPerformed(evt);
            }
        });
        jPingreso.add(jTApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, -1));

        jComboBoxTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPingreso.add(jComboBoxTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, 30));

        jBIngresoDireccion.setText("Ingresar");
        jPingreso.add(jBIngresoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 73, -1, 30));

        jPanel1.add(jPingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 660, 390));

        jPtabla.setBackground(new java.awt.Color(255, 255, 255));
        jPtabla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPtabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCliente.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTableCliente.setForeground(new java.awt.Color(51, 51, 51));
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombres", "Correo", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCliente.setColumnSelectionAllowed(true);
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCliente);
        jTableCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPtabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 150));

        jPanel1.add(jPtabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 660, 150));

        jPbotones.setBackground(new java.awt.Color(255, 255, 255));
        jPbotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPbotones.setForeground(new java.awt.Color(102, 102, 102));
        jPbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBnuevo.setBackground(new java.awt.Color(238, 112, 82));
        jBnuevo.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBnuevo.setForeground(new java.awt.Color(238, 112, 82));
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBnuevo.setContentAreaFilled(false);
        jBnuevo.setDefaultCapable(false);
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPbotones.add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, 30));

        jBmodificar.setBackground(new java.awt.Color(238, 112, 82));
        jBmodificar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(238, 112, 82));
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBmodificar.setContentAreaFilled(false);
        jPbotones.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 30));

        jBeliminar.setBackground(new java.awt.Color(238, 112, 82));
        jBeliminar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(238, 112, 82));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBeliminar.setContentAreaFilled(false);
        jPbotones.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 70, 30));

        jPanel1.add(jPbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 660, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCuentaActivoBoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCuentaActivoBoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCuentaActivoBoolActionPerformed

    private void jTClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTClienteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClienteIDActionPerformed

    private void jTnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreClienteActionPerformed

    private void jTCorreoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCorreoClienteActionPerformed

    private void jTDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDireccionActionPerformed

    private void jTFechaCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaCreacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaCreacionActionPerformed

    private void jBTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTiendaActionPerformed

    private void jTApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidosActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        //Se llama a este Metodo cuando se selecciona un elemento de la tabla
        
        
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jTActivoIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTActivoIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTActivoIntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngresoDireccion;
    private javax.swing.JButton jBTienda;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JComboBox<String> jComboBoxTienda;
    private javax.swing.JLabel jLApellidos;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLCuentaActivoBool;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTienda;
    private javax.swing.JLabel jLactivo;
    private javax.swing.JLabel jLfechaCreacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPingreso;
    private javax.swing.JPanel jPtabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTActivoInt;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTClienteID;
    private javax.swing.JTextField jTCorreoCliente;
    private javax.swing.JTextField jTCuentaActivoBool;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTFechaCreacion;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTnombreCliente;
    // End of variables declaration//GEN-END:variables

    public JButton getjBeliminar() {
        return jBeliminar;
    }

    public JButton getjBmodificar() {
        return jBmodificar;
    }

    public JButton getjBnuevo() {
        return jBnuevo;
    }

    public JButton getjButton2() {
        return jBTienda;
    }

    public JTable getjTableCliente() {
        return jTableCliente;
    }

    public JTextField getjTnombreCliente() {
        return jTnombreCliente;
    }

    public JTextField getjTDireccion() {
        return jTDireccion;
    }

    public JTextField getjTFechaCreacion() {
        return jTFechaCreacion;
    }

    public JTextField getjTActivoInt() {
        return jTActivoInt;
    }

    public JTextField getjTCuentaActivoBool() {
        return jTCuentaActivoBool;
    }

    public JTextField getjTApellidos() {
        return jTApellidos;
    }

    public JTextField getjTCorreoCliente() {
        return jTCorreoCliente;
    }

    public JTextField getjTClienteID() {
        return jTClienteID;
    }

    public JButton getjBTienda() {
        return jBTienda;
    }

    public JComboBox<String> getjComboBoxTienda() {
        return jComboBoxTienda;
    }

    public void addListenerBtnNuevo(ActionListener listenCliente) {
        jBnuevo.addActionListener(listenCliente);
    }

    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }
    
    public void addListenerTabla(MouseListener listener)
    {
        jTableCliente.addMouseListener(listener);
        
    }

    public void cargarClientesTabla(ArrayList<Cliente> listadoCliente) {
        DefaultTableModel defaultCombo;
        defaultCombo = (DefaultTableModel) jTableCliente.getModel();
        limpiarListadoTabla();
        for (int i = 0; i < listadoCliente.size(); i++) {
            defaultCombo.addRow(new Object[]{
                listadoCliente.get(i).getClienteID(),
                listadoCliente.get(i).getNombreCliente() + " " + listadoCliente.get(i).getApellidoCliente(),
                listadoCliente.get(i).getCorreoCliente(),
                listadoCliente.get(i).getDireccionCliente(),});
        }
        
        //Muestra en el campo de texto de la Interfaz el ID cliente Consecutivo
        int valor = Integer.parseInt(""+defaultCombo.getValueAt(defaultCombo.getRowCount()-1, 0))+1;
        jTClienteID.setText(""+valor);
        jTClienteID.setEnabled(false);
    }
    
    //Carga el listado de tiendas al combobox Tienda
    public void cargarTiendasCombo(ArrayList<Tienda> listadoTienda)
     {
         DefaultComboBoxModel model;
         
         String[] arregloTiendas = new String[listadoTienda.size()];
         //ArrayList <Integer> arreglotiendas; 
         
         for(int a=0; a < listadoTienda.size();a++)
         {
             arregloTiendas[a] = "Sede no. " +listadoTienda.get(a).getTiendaID();
             
         }
         
         model = new DefaultComboBoxModel(arregloTiendas);
         
         jComboBoxTienda.setModel(model);
     }
    

    private void limpiarListadoTabla() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTableCliente.getModel();
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

   
    

}
