/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InternalFrame;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import Modelo.*;
import java.awt.event.MouseListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nicol
 */
public class iFempleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form iFempleado
     */
    public iFempleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEmpleado = new javax.swing.JPanel();
        jPingreso = new javax.swing.JPanel();
        jTNombreUsuario = new javax.swing.JTextField();
        jLEmpleadoID = new javax.swing.JLabel();
        jLNombreEmpleado = new javax.swing.JLabel();
        jLactivo = new javax.swing.JLabel();
        jTnombreEmpleado = new javax.swing.JTextField();
        jTCorreoEmpleado = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jLContrasena = new javax.swing.JLabel();
        jLCorreo = new javax.swing.JLabel();
        jLDireccion = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLApellidos = new javax.swing.JLabel();
        jTApellidosEmpleado = new javax.swing.JTextField();
        jCBTiendaID = new javax.swing.JComboBox<>();
        jPassContrasena = new javax.swing.JPasswordField();
        jBFoto = new javax.swing.JButton();
        jTEmpleadoID = new javax.swing.JTextField();
        jLTienda1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLUltimaActualizacion = new javax.swing.JLabel();
        jPtabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jPbotones = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();

        jPanelEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPingreso.setBackground(new java.awt.Color(255, 255, 255));
        jPingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Decker", 0, 14), new java.awt.Color(238, 112, 82))); // NOI18N
        jPingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTNombreUsuario.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTNombreUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTNombreUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreUsuarioActionPerformed(evt);
            }
        });
        jPingreso.add(jTNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 250, 20));

        jLEmpleadoID.setBackground(new java.awt.Color(238, 112, 82));
        jLEmpleadoID.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLEmpleadoID.setForeground(new java.awt.Color(51, 51, 51));
        jLEmpleadoID.setText("Empleado ID:");
        jPingreso.add(jLEmpleadoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLNombreEmpleado.setBackground(new java.awt.Color(238, 112, 82));
        jLNombreEmpleado.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLNombreEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        jLNombreEmpleado.setText("Nombres:");
        jPingreso.add(jLNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLactivo.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLactivo.setForeground(new java.awt.Color(51, 51, 51));
        jLactivo.setText("Nombre de Usuario:");
        jPingreso.add(jLactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jTnombreEmpleado.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTnombreEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        jTnombreEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTnombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreEmpleadoActionPerformed(evt);
            }
        });
        jPingreso.add(jTnombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 20));

        jTCorreoEmpleado.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTCorreoEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        jTCorreoEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCorreoEmpleadoActionPerformed(evt);
            }
        });
        jPingreso.add(jTCorreoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 240, 20));

        jTDireccion.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTDireccion.setForeground(new java.awt.Color(102, 102, 102));
        jTDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDireccionActionPerformed(evt);
            }
        });
        jPingreso.add(jTDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 240, 20));

        jLContrasena.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLContrasena.setForeground(new java.awt.Color(51, 51, 51));
        jLContrasena.setText("Contraseña:");
        jPingreso.add(jLContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLCorreo.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLCorreo.setForeground(new java.awt.Color(51, 51, 51));
        jLCorreo.setText("Correo:");
        jPingreso.add(jLCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 50, -1));

        jLDireccion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jLDireccion.setText("Direccion:");
        jPingreso.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPingreso.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 20, 20));

        jLApellidos.setBackground(new java.awt.Color(238, 112, 82));
        jLApellidos.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLApellidos.setForeground(new java.awt.Color(51, 51, 51));
        jLApellidos.setText("Apellidos:");
        jPingreso.add(jLApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jTApellidosEmpleado.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTApellidosEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        jTApellidosEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTApellidosEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidosEmpleadoActionPerformed(evt);
            }
        });
        jPingreso.add(jTApellidosEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, -1));

        jCBTiendaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPingreso.add(jCBTiendaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 190, -1));
        jPingreso.add(jPassContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 250, 20));

        jBFoto.setText("Picture");
        jBFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFotoActionPerformed(evt);
            }
        });
        jPingreso.add(jBFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 120));
        jPingreso.add(jTEmpleadoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, -1));

        jLTienda1.setBackground(new java.awt.Color(238, 112, 82));
        jLTienda1.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLTienda1.setForeground(new java.awt.Color(51, 51, 51));
        jLTienda1.setText("Tienda:");
        jPingreso.add(jLTienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, 20));

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPingreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, -1));

        jLabel2.setText("Ultima Actualización:");
        jPingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));
        jPingreso.add(jLUltimaActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 324, 150, 30));

        jPanelEmpleado.add(jPingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 660, 390));

        jPtabla.setBackground(new java.awt.Color(255, 255, 255));
        jPtabla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPtabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEmpleado.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTableEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Empleado", "Nombres", "Username", "Direccion", "Tienda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEmpleado.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTableEmpleado);
        jTableEmpleado.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPtabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 660, 140));

        jPanelEmpleado.add(jPtabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 660, 150));

        jPbotones.setBackground(new java.awt.Color(255, 255, 255));
        jPbotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPbotones.setForeground(new java.awt.Color(102, 102, 102));
        jPbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBnuevo.setBackground(new java.awt.Color(238, 112, 82));
        jBnuevo.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBnuevo.setForeground(new java.awt.Color(238, 112, 82));
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBnuevo.setContentAreaFilled(false);
        jBnuevo.setDefaultCapable(false);
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPbotones.add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, 30));

        jBmodificar.setBackground(new java.awt.Color(238, 112, 82));
        jBmodificar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(238, 112, 82));
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBmodificar.setContentAreaFilled(false);
        jPbotones.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 30));

        jBeliminar.setBackground(new java.awt.Color(238, 112, 82));
        jBeliminar.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(238, 112, 82));
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 112, 82)));
        jBeliminar.setContentAreaFilled(false);
        jPbotones.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 70, 30));

        jPanelEmpleado.add(jPbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 660, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelEmpleado.getAccessibleContext().setAccessibleName("Datos Empleado");
        jPanelEmpleado.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreUsuarioActionPerformed

    private void jTnombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreEmpleadoActionPerformed

    private void jTCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCorreoEmpleadoActionPerformed

    private void jTDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDireccionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTApellidosEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidosEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidosEmpleadoActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jBFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFotoActionPerformed
        // TODO add your handling code here:
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = 
                new FileNameExtensionFilter("png", "jpg", "jpeg");
        fileChooser.setFileFilter(filtro);
        fileChooser.setMultiSelectionEnabled(true);
        
//        int seleccion= fileChooser.showOpenDialog(this);
//        if(seleccion != JFileChooser.CANCEL_OPTION){
            //File[] archivos = fileChooser.getSelectedFiles(); 
        
        
    }//GEN-LAST:event_jBFotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargarTiendasCombo(ArrayList<Tienda> listadoTiendas){ 
       DefaultComboBoxModel model; 
         
         String [] arregloActores = new String [listadoTiendas.size()];
         
         for(int a = 0; a < listadoTiendas.size(); a++)
         {
             arregloActores[a] = "Sede no. "+listadoTiendas.get(a).getTiendaID();
         }
         model = new DefaultComboBoxModel(arregloActores);
         
         jCBTiendaID.setModel(model); 
    }
    
    
    
    
    public void cargarEmpleadosTabla(ArrayList<Empleado> listadoEmpleado)
    {
        //System.err.println(listadoEmpleado.get(3).getContrasenaEmpleado());
         DefaultTableModel defaultcombo;
        defaultcombo = (DefaultTableModel) jTableEmpleado.getModel();        
        limpiarListadoTabla();
        for(int i= 0; i < listadoEmpleado.size(); i++){
              defaultcombo.addRow(new Object[]{
              listadoEmpleado.get(i).getEmpleadoID(),
              listadoEmpleado.get(i).getNombreEmpleado(),
              listadoEmpleado.get(i).getNombreUsuarioEmpleado(),
              listadoEmpleado.get(i).getDireccionID_Empleado(),
        });}
        
        
        //Muestra en el campo de texto de la Interfaz el ID cliente Consecutivo
        int valor = Integer.parseInt(""+defaultcombo.getValueAt(defaultcombo.getRowCount()-1, 0))+1;
        jTEmpleadoID.setText(""+valor);
        jTEmpleadoID.setEnabled(false);
        
    }
    
    private void limpiarListadoTabla(){
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTableEmpleado.getModel();
        for(int i=modelo.getRowCount()-1; i>=0 ; i--){
            modelo.removeRow(i);
        }
    }
    
     public void gestionMensajes(String mensaje, String titulo, int icono){
         JOptionPane.showMessageDialog(this,mensaje, titulo, icono);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFoto;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBTiendaID;
    private javax.swing.JLabel jLApellidos;
    private javax.swing.JLabel jLContrasena;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEmpleadoID;
    private javax.swing.JLabel jLNombreEmpleado;
    private javax.swing.JLabel jLTienda1;
    private javax.swing.JLabel jLUltimaActualizacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLactivo;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JPasswordField jPassContrasena;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPingreso;
    private javax.swing.JPanel jPtabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTApellidosEmpleado;
    private javax.swing.JTextField jTCorreoEmpleado;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTEmpleadoID;
    private javax.swing.JTextField jTNombreUsuario;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTextField jTnombreEmpleado;
    // End of variables declaration//GEN-END:variables

    
    public void AddListenerTabala(MouseListener ml){
        jTableEmpleado.addMouseListener(ml);
    }
    
    public JButton getjBeliminar() {
        return jBeliminar;
    }

    public JButton getjBmodificar() {
        return jBmodificar;
    }

    public JButton getjBnuevo() {
        return jBnuevo;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public JComboBox<String> getjCBTiendaID() {
        return jCBTiendaID;
    }

    public JPasswordField getjPassContrasena() {
        return jPassContrasena;
    }

    public JTextField getjTApellidosEmpleado() {
        return jTApellidosEmpleado;
    }

    public JTextField getjTCorreoEmpleado() {
        return jTCorreoEmpleado;
    }

    public JLabel getjLUltimaActualizacion() {
        return jLUltimaActualizacion;
    }

    

    public JTextField getjTDireccion() {
        return jTDireccion;
    }

    public JTextField getjTNombreUsuario() {
        return jTNombreUsuario;
    }

    public JTable getjTableCliente() {
        return jTableEmpleado;
    }

    public JTextField getjTnombreEmpleado() {
        return jTnombreEmpleado;
    }

    public JTextField getjTEmpleadoID() {
        return jTEmpleadoID;
    }

   

    













}
